/*
 * File: app/controller/MenuController.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('webapp.controller.MenuController', {
    extend: 'Ext.app.Controller',

    onTreepanelItemClick: function(dataview, record, item, index, e, eOpts) {
        //alert(record.get("text"));
        var menuId = record.get("menuId");

        if(menuId !== undefined){
            this.showMenu(menuId);
        }

    },

    showMenu: function(menuId) {
        var activeItem = -1;

        if(menuId === "dashboard"){
            activeItem = 0;

        }else if(menuId === "tomcatInsts"){
            activeItem = 1;

        }else if(menuId === "dbcp"){
            activeItem = 2;

        }else if(menuId === "templet"){
            activeItem = 3;

        }else if(menuId === "ssncluster"){
            activeItem = 4;

        }else if(menuId === "apmDash"){
            activeItem = 5;

        }else if(menuId === "apmAnaly"){
            activeItem = 6;
        }

        if(activeItem > -1){
            Ext.getCmp("centerContainer").layout.setActiveItem(activeItem);
        }
    },

    init: function(application) {
        this.control({
            "#menuTreePanel": {
                itemclick: this.onTreepanelItemClick
            }
        });
    }

});
