/*
 * File: app/view/dashboardPanel.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('webapp.view.dashboardPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.dashboardpanel',

    requires: [
        'Ext.panel.Panel',
        'Ext.toolbar.Toolbar',
        'Ext.Img',
        'Ext.form.Label',
        'Ext.form.FieldContainer',
        'Ext.form.field.Display',
        'Ext.panel.Tool'
    ],

    itemId: 'dashboardPanel',
    layout: 'border',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    flex: 1,
                    region: 'center',
                    id: 'monitoringPanel',
                    itemId: 'monitoringPanel',
                    title: 'System Monitoring',
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'panel',
                            flex: 1,
                            id: 'memoryPanel',
                            itemId: 'memoryPanel',
                            layout: 'fit'
                        },
                        {
                            xtype: 'panel',
                            flex: 1,
                            id: 'cpuPanel',
                            itemId: 'cpuPanel',
                            layout: 'fit'
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    flex: 1,
                    region: 'south',
                    split: true,
                    height: 150,
                    id: 'statPanel',
                    itemId: 'statPanel',
                    collapsible: true,
                    title: 'Infinispan Statistics',
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'panel',
                            margins: '5 5 5 5',
                            layout: {
                                type: 'vbox',
                                align: 'stretch'
                            },
                            dockedItems: [
                                {
                                    xtype: 'toolbar',
                                    flex: 1,
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'image',
                                            height: 32,
                                            width: 32,
                                            src: 'resources/images/icon/session.png'
                                        },
                                        {
                                            xtype: 'label',
                                            id: 'totalField',
                                            itemId: 'totalField',
                                            style: '{text-align: center;font-size: 15pt;}',
                                            text: 'Totally 0 Session Data Saved in Cache'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            flex: 2,
                            margins: '5 5 5 5',
                            itemId: 'statContainer',
                            layout: {
                                type: 'hbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'fieldcontainer',
                                    flex: 1,
                                    height: 120,
                                    width: 400,
                                    items: [
                                        {
                                            xtype: 'displayfield',
                                            id: 'statField1',
                                            itemId: 'statField1',
                                            fieldLabel: 'Time Since Start(sec)',
                                            labelWidth: 170
                                        },
                                        {
                                            xtype: 'displayfield',
                                            id: 'statField2',
                                            itemId: 'statField2',
                                            fieldLabel: 'Total Number of Entries',
                                            labelWidth: 170
                                        },
                                        {
                                            xtype: 'displayfield',
                                            id: 'statField3',
                                            itemId: 'statField3',
                                            fieldLabel: 'Current Number of Entries',
                                            labelWidth: 170
                                        }
                                    ]
                                },
                                {
                                    xtype: 'fieldcontainer',
                                    flex: 1,
                                    height: 120,
                                    width: 400,
                                    items: [
                                        {
                                            xtype: 'displayfield',
                                            id: 'statField4',
                                            itemId: 'statField4',
                                            fieldLabel: 'Stores'
                                        },
                                        {
                                            xtype: 'displayfield',
                                            id: 'statField5',
                                            itemId: 'statField5',
                                            fieldLabel: 'Retrivals'
                                        },
                                        {
                                            xtype: 'displayfield',
                                            id: 'statField6',
                                            itemId: 'statField6',
                                            fieldLabel: 'Hits'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'fieldcontainer',
                                    flex: 1,
                                    height: 120,
                                    width: 400,
                                    items: [
                                        {
                                            xtype: 'displayfield',
                                            id: 'statField7',
                                            itemId: 'statField7',
                                            fieldLabel: 'Misses',
                                            labelWidth: 130
                                        },
                                        {
                                            xtype: 'displayfield',
                                            id: 'statField8',
                                            itemId: 'statField8',
                                            fieldLabel: 'Remove Hits',
                                            labelWidth: 130
                                        },
                                        {
                                            xtype: 'displayfield',
                                            id: 'statField9',
                                            itemId: 'statField9',
                                            fieldLabel: 'Remove Misses',
                                            labelWidth: 130
                                        }
                                    ]
                                }
                            ]
                        }
                    ],
                    tools: [
                        {
                            xtype: 'tool',
                            id: 'statRefreshTool',
                            itemId: 'statRefreshTool',
                            type: 'refresh'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});