/*
 * File: app/view/MyTreePanel29.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('webapp.view.MyTreePanel29', {
    extend: 'Ext.tree.Panel',
    alias: 'widget.mytreepanel29',

    requires: [
        'Ext.tree.View',
        'Ext.selection.RowModel'
    ],

    id: 'viewTreePanel',
    itemId: 'viewTreePanel',
    width: 250,
    autoScroll: true,
    collapsible: false,
    store: 'viewTreeStore',
    rootVisible: false,
    useArrows: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            viewConfig: {
                id: 'viewTreeView',
                itemId: 'viewTreeView',
                autoScroll: true
            },
            selModel: Ext.create('Ext.selection.RowModel', {
                listeners: {
                    select: {
                        fn: me.onRowModelSelect,
                        scope: me
                    }
                }
            })
        });

        me.callParent(arguments);
    },

    onRowModelSelect: function(rowmodel, record, index, eOpts) {
        if (record.data.leaf) {
            Ext.getCmp('mapPanel').setTitle('Map ' + '(' + record.data.id + ')');
            Ext.getCmp('reducePanel').setTitle('Reduce ' + '(' + record.data.id + ')');
        } else {
            Ext.getCmp('mapPanel').setTitle('Map');
            Ext.getCmp('reducePanel').setTitle('Reduce');
        }

        Ext.getCmp('mapTextArea').setValue(record.data.map);
        Ext.getCmp('reduceTextArea').setValue(record.data.reduce);

        /*
        //Ext.getCmp('mapTextArea').update(selected[selected.length - 1].data.map.replace(/\n/gi, '</br>').replace(/ /gi, '&nbsp;'));

        if (selected.length > 0) {
            Ext.getCmp('mapTextArea').setValue(selected[selected.length - 1].data.map);
            Ext.getCmp('reduceTextArea').setValue(selected[selected.length - 1].data.reduce);
        }
        */
    }

});