/*
 * File: app/view/sessionDataPanel.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('webapp.view.sessionDataPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.sessiondatapanel',

    requires: [
        'Ext.grid.Panel',
        'Ext.grid.column.Action',
        'Ext.panel.Tool',
        'Ext.form.field.Display'
    ],

    id: 'sessionDataPanel',
    itemId: 'sessionDataPanel',
    layout: 'border',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'gridpanel',
                    flex: 1,
                    region: 'center',
                    id: 'sessionDataGrid',
                    itemId: 'sessionDataGrid',
                    autoScroll: true,
                    title: 'Session List',
                    emptyText: 'No Cache Keys',
                    forceFit: true,
                    store: 'sessionDataStore',
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'key',
                            text: 'Key',
                            flex: 1
                        },
                        {
                            xtype: 'actioncolumn',
                            width: 50,
                            align: 'center',
                            menuDisabled: true,
                            items: [
                                {
                                    handler: function(view, rowIndex, colIndex, item, e, record, row) {
                                        var sessionDataGrid = Ext.getCmp('sessionDataGrid'),
                                            detailPanel = Ext.getCmp('detailPanel');

                                        Ext.Msg.confirm('Confirm', 'Are you sure you want to delete this session?', function(btn) {
                                            if (btn == 'yes') {
                                                sessionDataGrid.setLoading(true);

                                                Ext.Ajax.request({
                                                    url: GlobalData.urlPrefix + 'deleteSessionData?key=' + record.get('key'),
                                                    params: {
                                                    },
                                                    success: function(response, opts){
                                                        sessionDataGrid.setLoading(false);

                                                        var store = Ext.data.StoreManager.lookup('sessionDataStore');
                                                        store.removeAt(rowIndex);

                                                        //Ext.getCmp('refreshTool').fireEvent('click');
                                                    },
                                                    failure: function(response, opts) {
                                                        sessionDataGrid.setLoading(false);
                                                        Ext.Msg.alert('Error', 'Server-side failure with status code ' + response.status);
                                                    }
                                                });
                                            }
                                        });
                                    },
                                    icon: 'resources/images/icon/delete.png',
                                    tooltip: 'Delete Session Data'
                                }
                            ]
                        }
                    ],
                    tools: [
                        {
                            xtype: 'tool',
                            id: 'searchTool',
                            itemId: 'searchTool',
                            type: 'search'
                        },
                        {
                            xtype: 'tool',
                            id: 'refreshTool',
                            itemId: 'refreshTool',
                            type: 'refresh'
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    flex: 1,
                    region: 'east',
                    split: true,
                    id: 'detailPanel',
                    itemId: 'detailPanel',
                    width: 150,
                    autoScroll: true,
                    layout: 'fit',
                    animCollapse: false,
                    collapsed: false,
                    collapsible: true,
                    title: 'Session Detail',
                    items: [
                        {
                            xtype: 'displayfield',
                            itemId: 'sessionDataField',
                            margin: '5 5 5 5',
                            overflowX: 'auto',
                            overflowY: 'auto'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});