/*
 * File: app/view/TomcatMngContainer.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('webapp.view.TomcatMngContainer', {
    extend: 'Ext.container.Container',
    alias: 'widget.tomcatmngcontainer',

    requires: [
        'Ext.grid.Panel',
        'Ext.grid.View',
        'Ext.grid.column.Column',
        'Ext.toolbar.Paging',
        'Ext.tab.Panel',
        'Ext.tab.Tab'
    ],

    layout: 'border',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'gridpanel',
                    region: 'center',
                    title: 'Tomcat Instances',
                    forceFit: true,
                    store: 'TomcatInstanceListStore',
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            width: 30,
                            dataIndex: 'id',
                            text: 'ID'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'instanceName',
                            text: 'Instance Name'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 70,
                            dataIndex: 'ipAddr',
                            text: 'IP Address'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 70,
                            dataIndex: 'httpPort',
                            text: 'HTTP Port'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 60,
                            dataIndex: 'applications',
                            text: 'Applications'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 40,
                            dataIndex: 'state',
                            text: '상태'
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            items: [
                                {
                                    xtype: 'button',
                                    id: 'createTomcatInstBtn',
                                    text: 'MyButton'
                                }
                            ]
                        },
                        {
                            xtype: 'pagingtoolbar',
                            dock: 'bottom',
                            width: 360,
                            displayInfo: true,
                            store: 'TomcatInstanceListStore'
                        }
                    ]
                },
                {
                    xtype: 'tabpanel',
                    flex: 1,
                    region: 'south',
                    split: true,
                    height: 150,
                    id: 'tomcatInstTabPanel',
                    itemId: 'tomcatInstTabPanel',
                    activeTab: 0,
                    items: [
                        {
                            xtype: 'panel',
                            title: '구성정보'
                        },
                        {
                            xtype: 'panel',
                            title: 'env.sh'
                        },
                        {
                            xtype: 'panel',
                            title: 'server.xml'
                        },
                        {
                            xtype: 'panel',
                            title: 'context.xml'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});